/* ---------------------------------------------------------------------------
   Hero cue — the pen stroke around the portrait.

   This path is NOT generated by maths. It was drawn by hand on paper,
   photographed, and traced: the ink was thresholded, thinned down to a
   one-pixel-wide skeleton, and then walked from one end to the other. What is
   stored below are those traced points, normalised so the drawn circle has its
   centre at (0,0) and a radius of 1. Every wobble is the real one from the pen.

   Two drawings are stored. Switch between them with GESTURE below.
   --------------------------------------------------------------------------- */

const GESTURE = '8471';   // '8471' = tight bumps, long tail | '8472' = bigger W, steeper flick

const CUE = {
  drawMs:      1150,   // time to draw the circle (steady, deliberate)
  flickMs:      420,   // time to draw the flourish (shorter = snappier)
  delayMs:      500,   // pause after load before the pen starts
};

const GESTURES = {
  '8471': {
    ringGap: 22,        // px between the photo's edge and the drawn circle
    flourishAt: 0.88,   // fraction of the stroke where the flourish begins
    points: [
      [-0.4766,-0.8957], [-0.3620,-0.9422], [-0.2275,-0.9819], [-0.0885,-1.0030], [0.0034,-1.0075],
      [0.1222,-0.9985], [0.2365,-0.9771], [0.3082,-0.9559], [0.3867,-0.9265], [0.5055,-0.8717],
      [0.6086,-0.8019], [0.6668,-0.7520], [0.7072,-0.7116], [0.8090,-0.5906], [0.8708,-0.4987],
      [0.9163,-0.4135], [0.9598,-0.3014], [0.9861,-0.1849], [0.9986,-0.0549], [0.9941,0.1065],
      [0.9704,0.2343], [0.9384,0.3396], [0.8827,0.4629], [0.8193,0.5660], [0.7453,0.6601],
      [0.6422,0.7632], [0.5548,0.8321], [0.4763,0.8788], [0.3306,0.9419], [0.2275,0.9704],
      [0.0818,0.9941], [-0.0347,0.9963], [-0.1849,0.9813], [-0.2835,0.9554], [-0.4023,0.9153],
      [-0.4696,0.8827], [-0.5659,0.8279], [-0.6511,0.7687], [-0.6937,0.7319], [-0.7565,0.6691],
      [-0.8202,0.5906], [-0.8596,0.5324], [-0.8938,0.4718], [-0.9162,0.4270], [-0.9489,0.3441],
      [-0.9710,0.2858], [-0.9969,0.1962], [-1.0120,0.0886], [-1.0165,0.0280], [-1.0165,-0.0773],
      [-1.0120,-0.1580], [-1.0024,-0.2252], [-0.9867,-0.2745], [-0.9649,-0.3126], [-0.9425,-0.3283],
      [-0.9044,-0.3373], [-0.8925,-0.3508], [-0.8932,-0.4135], [-0.9044,-0.4785], [-0.8993,-0.5032],
      [-0.8909,-0.5115], [-0.8775,-0.5109], [-0.8259,-0.4625], [-0.8058,-0.4561], [-0.7971,-0.4609],
      [-0.7946,-0.4897], [-0.8131,-0.5682], [-0.8147,-0.5951], [-0.8029,-0.6444], [-0.7958,-0.6556],
      [-0.7856,-0.6623], [-0.7766,-0.6613], [-0.7664,-0.6533], [-0.7308,-0.5906], [-0.7004,-0.5611],
      [-0.6690,-0.5525], [-0.6578,-0.5557], [-0.6479,-0.5640], [-0.6431,-0.5749], [-0.6421,-0.6040],
      [-0.6578,-0.7116], [-0.6521,-0.7856], [-0.6338,-0.8461], [-0.6034,-0.8954], [-0.5723,-0.9338],
    ],
  },
  '8472': {
    ringGap: 18,        // px between the photo's edge and the drawn circle
    flourishAt: 0.85,   // fraction of the stroke where the flourish begins
    points: [
      [-0.4778,-0.8633], [-0.4263,-0.8963], [-0.2707,-0.9529], [-0.2173,-0.9678], [-0.1462,-0.9808],
      [-0.0439,-0.9913], [0.0273,-0.9913], [0.0851,-0.9869], [0.2140,-0.9675], [0.3430,-0.9291],
      [0.4386,-0.8897], [0.5609,-0.8201], [0.6521,-0.7544], [0.7188,-0.6956], [0.8198,-0.5778],
      [0.8811,-0.4821], [0.9297,-0.3865], [0.9671,-0.2776], [0.9932,-0.1664], [1.0078,-0.0708],
      [1.0100,0.0293], [1.0056,0.0737], [0.9776,0.2205], [0.9560,0.2961], [0.9297,0.3628],
      [0.8817,0.4650], [0.8299,0.5540], [0.7864,0.6185], [0.7076,0.7163], [0.5965,0.8135],
      [0.4875,0.8748], [0.3941,0.9158], [0.2029,0.9777], [0.0651,1.0009], [-0.0595,1.0031],
      [-0.2018,0.9793], [-0.3085,0.9514], [-0.3908,0.9209], [-0.4552,0.8904], [-0.5664,0.8227],
      [-0.6620,0.7452], [-0.7471,0.6540], [-0.8351,0.5406], [-0.8961,0.4406], [-0.9301,0.3739],
      [-0.9660,0.2783], [-0.9892,0.1782], [-1.0000,0.0604], [-0.9978,-0.0686], [-0.9787,-0.1975],
      [-0.9441,-0.3243], [-0.9225,-0.3799], [-0.8370,-0.6489], [-0.8189,-0.6912], [-0.7932,-0.7166],
      [-0.7799,-0.7159], [-0.7684,-0.7067], [-0.7608,-0.6889], [-0.7576,-0.6645], [-0.7548,-0.5711],
      [-0.7503,-0.5625], [-0.7421,-0.5584], [-0.7306,-0.5666], [-0.7109,-0.6111], [-0.6877,-0.7223],
      [-0.6706,-0.7779], [-0.6598,-0.7941], [-0.6531,-0.7957], [-0.6395,-0.7861], [-0.6182,-0.7833],
      [-0.5810,-0.7156], [-0.5642,-0.6994], [-0.5527,-0.6988], [-0.5508,-0.7134], [-0.5686,-0.8201],
      [-0.5651,-0.8757], [-0.5553,-0.9157], [-0.5404,-0.9535], [-0.5032,-1.0161],
    ],
  },
};

const HERO = document.querySelector('.hero');
const PORTRAIT = document.querySelector('.portrait');
const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

// Catmull-Rom spline through `points`, written out as cubic-Bezier ("C") commands.
// Each segment's control points come from its neighbours, so the tangents match
// at every join — the curve passes through all the traced points with no corners.
function smoothPathThrough(points) {
  let d = `M ${points[0].x} ${points[0].y}`;
  for (let i = 0; i < points.length - 1; i++) {
    const p0 = points[i - 1] || points[i];
    const p1 = points[i];
    const p2 = points[i + 1];
    const p3 = points[i + 2] || p2;
    d += ` C ${p1.x + (p2.x - p0.x) / 6} ${p1.y + (p2.y - p0.y) / 6},`
       + ` ${p2.x - (p3.x - p1.x) / 6} ${p2.y - (p3.y - p1.y) / 6},`
       + ` ${p2.x} ${p2.y}`;
  }
  return d;
}

// Scale the normalised drawing onto the live portrait: radius 1 becomes the
// ring just outside the photo, and (0,0) becomes the photo's centre.
function buildPath() {
  const heroRect = HERO.getBoundingClientRect();
  const portraitRect = PORTRAIT.getBoundingClientRect();
  const g = GESTURES[GESTURE];

  const cx = portraitRect.left + portraitRect.width / 2 - heroRect.left;
  const cy = portraitRect.top + portraitRect.height / 2 - heroRect.top;
  const ring = portraitRect.width / 2 + g.ringGap;

  return smoothPathThrough(g.points.map(([x, y]) => ({ x: cx + x * ring, y: cy + y * ring })));
}

let cuePath = null;

function playHeroCue() {
  if (!HERO || !PORTRAIT) return;

  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.classList.add('hero-cue');
  svg.setAttribute('aria-hidden', 'true');

  cuePath = document.createElementNS('http://www.w3.org/2000/svg', 'path');
  cuePath.setAttribute('d', buildPath());
  svg.appendChild(cuePath);
  HERO.appendChild(svg);

  const total = cuePath.getTotalLength();
  cuePath.style.strokeDasharray = total;

  if (prefersReducedMotion) {
    cuePath.style.strokeDashoffset = 0;   // show it drawn, skip the motion
    return;
  }

  const flourish = total * (1 - GESTURES[GESTURE].flourishAt);
  cuePath.style.strokeDashoffset = total;

  // Phase 1 — the circle, drawn at a steady deliberate pace.
  setTimeout(() => {
    cuePath.style.transition = `stroke-dashoffset ${CUE.drawMs}ms cubic-bezier(0.36, 0.02, 0.30, 1)`;
    cuePath.style.strokeDashoffset = flourish;
  }, CUE.delayMs);

  // Phase 2 — the flourish, noticeably faster.
  setTimeout(() => {
    cuePath.style.transition = `stroke-dashoffset ${CUE.flickMs}ms cubic-bezier(0.5, 0, 0.75, 0.9)`;
    cuePath.style.strokeDashoffset = 0;
  }, CUE.delayMs + CUE.drawMs);
}

// The path is scaled from live measurements, so a resize would leave it stale.
// Rebuild it in place (no replay — the moment has passed).
function rebuildHeroCue() {
  if (!cuePath) return;
  cuePath.setAttribute('d', buildPath());
  cuePath.style.transition = 'none';
  cuePath.style.strokeDasharray = cuePath.getTotalLength();
  cuePath.style.strokeDashoffset = 0;
}

window.addEventListener('load', playHeroCue);
window.addEventListener('resize', rebuildHeroCue);
